### ISSUE TITLE
Bug: panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by platinum55** [harababurel/gcsf#63]
I dont know which operation exactly it is, but I keep getting this error(gcsf needs to be restarted after this):

 INFO  gcsf::gcsf::file_manager > Checking for changes and possibly applying them.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::panicking::panic
             at src/libcore/panicking.rs:59
   9: <core::option::Option<T>>::unwrap
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:20
  10: gcsf::gcsf::file_manager::FileManager::get_node_id
             at src/gcsf/file_manager.rs:291
  11: gcsf::gcsf::file_manager::FileManager::add_file_locally
             at src/gcsf/file_manager.rs:372
  12: gcsf::gcsf::file_manager::FileManager::sync
             at src/gcsf/file_manager.rs:129
  13: <gcsf::gcsf::filesystem::GCSF as fuse::Filesystem>::readdir
             at src/gcsf/filesystem.rs:179
  14: fuse::request::Request::dispatch
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/request.rs:311
  15: fuse::request::dispatch
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/request.rs:34
  16: <fuse::session::Session<FS>>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/session.rs:79
  17: fuse::session::BackgroundSession::new::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/session.rs:130
  18: thread_scoped::scoped::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/thread-scoped-1.0.2/src/lib.rs:76
 WARN  fuse::reply              > Reply not sent for operation 2235356, replying with I/O error

I will try to get the verbose backtrace soon :)

**Comment by platinum55** [comment]
### Full Backtrace

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
stack backtrace:
   0:     0x55e13e6cb1d3 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h00d1e05a61bd440b
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x55e13e6c51b8 - std::sys_common::backtrace::_print::hc0d53aca8da62f75
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x55e13e6c9a72 - std::panicking::default_hook::{{closure}}::h46d30bcc4bfff149
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:211
   3:     0x55e13e6c97dd - std::panicking::default_hook::h017696c2a8b7b16f
                               at src/libstd/panicking.rs:227
   4:     0x55e13e6ca180 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                               at src/libstd/panicking.rs:491
   5:     0x55e13e6c9d01 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                               at src/libstd/panicking.rs:398
   6:     0x55e13e6c9be5 - rust_begin_unwind
                               at src/libstd/panicking.rs:325
   7:     0x55e13e6e0cec - core::panicking::panic_fmt::h4d67173bc68f6d5a
                               at src/libcore/panicking.rs:95
   8:     0x55e13e6e0c1b - core::panicking::panic::h6f50c0de2dcd7974
                               at src/libcore/panicking.rs:59
   9:     0x55e13dc897fc - <core::option::Option<T>>::unwrap::h00bb0ec4f2095b04
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libcore/macros.rs:20
  10:     0x55e13de0d6d1 - gcsf::gcsf::file_manager::FileManager::get_node_id::h9b7b943640a49d59
                               at src/gcsf/file_manager.rs:291
  11:     0x55e13de0ecfb - gcsf::gcsf::file_manager::FileManager::add_file_locally::h3a44b9b1cf96884f
                               at src/gcsf/file_manager.rs:372
  12:     0x55e13de083ed - gcsf::gcsf::file_manager::FileManager::sync::h179eecf63bc0e726
                               at src/gcsf/file_manager.rs:129
  13:     0x55e13dc6a957 - <gcsf::gcsf::filesystem::GCSF as fuse::Filesystem>::readdir::h0102c905882ed157
                               at src/gcsf/filesystem.rs:179
  14:     0x55e13dbb9a76 - fuse::request::Request::dispatch::h40bdcdb946b445c8
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/request.rs:311
  15:     0x55e13dbc6c6c - fuse::request::dispatch::h6135f090c1e22f21
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/request.rs:34
  16:     0x55e13dbafe1a - <fuse::session::Session<FS>>::run::hc5cc21c6fdf9f1c2
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/session.rs:79
  17:     0x55e13dbb0675 - fuse::session::BackgroundSession::new::{{closure}}::he43a4458742a4dff
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/fuse-0.3.1/src/session.rs:130
  18:     0x55e13dbaec05 - thread_scoped::scoped::{{closure}}::h2d46aff7994f23a0
                               at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/thread-scoped-1.0.2/src/lib.rs:76
  19:     0x55e13db8f1c2 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd85cbcffba2c8510
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/sys_common/backtrace.rs:136
  20:     0x55e13dbd3972 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h0ebfc51b5b60ce2a
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:477
  21:     0x55e13db92f22 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha65f3c87cfea9280
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:319
  22:     0x55e13db91418 - std::panicking::try::do_call::he6b94b0f2154a06a
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:310
  23:     0x55e13e6da529 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:102
  24:     0x55e13db91290 - std::panicking::try::hae2fa3a110960655
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panicking.rs:289
  25:     0x55e13db92fda - std::panic::catch_unwind::h514c95572e0bf9b4
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/panic.rs:398
  26:     0x55e13dbd31ea - std::thread::Builder::spawn_unchecked::{{closure}}::h2560308c9a2b11c6
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/thread/mod.rs:476
  27:     0x55e13dbd3ca6 - <F as alloc::boxed::FnBox<A>>::call_box::h0e4755162ca0486d
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:673
  28:     0x55e13e6ce10d - std::sys::unix::thread::Thread::new::thread_start::hca8e72c41fa9d291
                               at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/liballoc/boxed.rs:683
                               at src/libstd/sys_common/thread.rs:24
                               at src/libstd/sys/unix/thread.rs:90
  29:     0x7ff2fae1f4a3 - start_thread
  30:     0x7ff2fa94ad0e - __clone
  31:                0x0 - <unknown>
 WARN  fuse::reply              > Reply not sent for operation 1339, replying with I/O error
^C INFO  gcsf                     > Ctrl-C detected

```
